import { useEffect, useMemo, useState } from 'react'

const navigation = ['About', 'Opportunities', 'Events', 'Insights', 'Community']
const opportunityTypes = ['All', 'Fellowships', 'Programmes', 'Events', 'Research']
const opportunities = [
  { type: 'Fellowships', organisation: 'Fellowship opportunity', title: 'Emerging Policy Leaders Fellowship', place: 'Remote · Asia', deadline: 'Deadline to be announced', tone: 'light' },
  { type: 'Programmes', organisation: 'Embassy programme', title: 'Youth Dialogue Programme', place: 'Chennai', deadline: 'Details coming soon', tone: 'ink' },
  { type: 'Events', organisation: 'Public dialogue', title: 'Young Voices in International Cooperation', place: 'Bengaluru', deadline: 'Date to be announced', tone: 'light' },
  { type: 'Research', organisation: 'Research opportunity', title: 'Research Associate Programme', place: 'Hyderabad · Hybrid', deadline: 'Details coming soon', tone: 'light' },
]
const pillars = [['01', 'Awareness', 'Making diplomacy, foreign policy and international pathways easier to understand.', 'Understand the world'], ['02', 'Opportunities', 'Bringing fellowships, exchanges and global programmes into clearer view.', 'Find your next step'], ['03', 'Connections', 'Creating meaningful access to people, ideas and institutions across borders.', 'Meet the network'], ['04', 'Advocacy', 'Supporting broader participation in the conversations that shape our shared future.', 'Widen the room']]
const focusAreas = ['Diplomacy & Foreign Policy', 'Youth & Leadership', 'Embassies & Missions', 'Education & Research', 'Global Opportunities', 'Regional-to-Global Connections']
function Arrow({ diagonal = false }: { diagonal?: boolean }) { return <span className={`arrow ${diagonal ? 'diagonal' : ''}`} aria-hidden="true">→</span> }
function Mark() { return <span className="brand-mark" aria-hidden="true"><i /><i /><i /></span> }
function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="section-label">{children}</p> }

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeType, setActiveType] = useState('All')
  const [activeNav, setActiveNav] = useState('about')
  const [isCompactHeader, setIsCompactHeader] = useState(false)
  const [motionReady, setMotionReady] = useState(false)
  const visible = useMemo(() => activeType === 'All' ? opportunities : opportunities.filter(({ type }) => type === activeType), [activeType])
  const closeMenu = () => setMenuOpen(false)
  useEffect(() => {
    const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches
    const frame = window.requestAnimationFrame(() => setMotionReady(true))
    const updateHeader = () => setIsCompactHeader(window.scrollY > 24)
    updateHeader()
    window.addEventListener('scroll', updateHeader, { passive: true })
    const sections = navigation.map((item) => document.getElementById(item.toLowerCase())).filter((section): section is HTMLElement => section !== null)
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) setActiveNav(entry.target.id)
      })
    }, { rootMargin: '-35% 0px -55% 0px', threshold: 0 })
    sections.forEach((section) => observer.observe(section!))
    if (!reduceMotion) {
      const reveals = document.querySelectorAll<HTMLElement>('.intro-layout, .pillars-heading, .opportunities-top, .approach-copy, .events-title, .insights-heading, .partner > div')
      const revealObserver = new IntersectionObserver((entries) => entries.forEach((entry) => {
        if (entry.isIntersecting) { entry.target.classList.add('is-visible'); revealObserver.unobserve(entry.target) }
      }), { rootMargin: '0px 0px -12% 0px', threshold: .08 })
      reveals.forEach((element) => { element.dataset.reveal = ''; revealObserver.observe(element) })
      return () => { window.cancelAnimationFrame(frame); window.removeEventListener('scroll', updateHeader); observer.disconnect(); revealObserver.disconnect() }
    }
    return () => { window.cancelAnimationFrame(frame); window.removeEventListener('scroll', updateHeader); observer.disconnect() }
  }, [])
  return <main>
    <header className={`site-header ${isCompactHeader ? 'is-compact' : ''}`}><a className="brand" href="#top" aria-label="South Diplomacy home"><Mark /><span>South<br />Diplomacy</span></a><nav className={menuOpen ? 'open' : ''} aria-label="Main navigation">{navigation.map((item) => { const id = item.toLowerCase(); return <a className={activeNav === id ? 'is-active' : ''} aria-current={activeNav === id ? 'page' : undefined} href={`#${id}`} key={item} onClick={closeMenu}>{item}</a> })}<a className="nav-partner" href="#partner" onClick={closeMenu}>Partner</a></nav><a className="header-cta" href="#community">Join the community <Arrow /></a><button className="menu-button" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><span /><span /></button></header>
    <section className={`hero ${motionReady ? 'is-ready' : ''}`} id="top" aria-labelledby="hero-title"><div className="hero-grid"><div className="hero-copy"><p className="eyebrow"><span /> India, outward</p><h1 id="hero-title"><span>Connecting</span><span><em>South India</em></span><span>with the world.</span></h1><p className="hero-intro">Global opportunities, foreign-policy context and international networks — closer to home.</p><div className="actions"><a className="button button-dark" href="#opportunities">Explore opportunities <Arrow /></a><a className="text-link" href="#community">Join the community <Arrow diagonal /></a></div></div><div className="hero-visual"><div className="photo-frame"><img src="https://images.unsplash.com/photo-1521292270410-a8c4d716d518?auto=format&fit=crop&w=1200&q=85" alt="Audience members in an international forum" /></div><p className="image-caption"><span>South India · globally engaged</span></p><div className="hero-stamp"><span>South<br />Diplomacy</span><i>✦</i><small>GLOBAL<br />AFFAIRS</small></div></div></div><div className="hero-footer"><p>For people and institutions taking part in India's international engagement.</p><a href="#about" aria-label="Discover South Diplomacy"><span>Scroll to discover</span><b>↓</b></a></div></section>
    <section className="intro" id="about"><SectionLabel>What we are here for</SectionLabel><div className="intro-layout"><h2>Diplomacy should not<br />depend on <em>geography.</em></h2><div><p>South Diplomacy brings international affairs into clearer view across South India — from fellowships and foreign policy to the institutions shaping global engagement.</p><a className="text-link" href="#approach">Our point of view <Arrow diagonal /></a></div></div></section>
    <section className="pillars" aria-labelledby="pillars-title"><div className="pillars-heading"><SectionLabel>Four ways forward</SectionLabel><h2 id="pillars-title">A more open<br />diplomatic <em>future.</em></h2></div><div className="pillar-list">{pillars.map(([number, title, text, label]) => <article className="pillar" key={number}><span className="pillar-number">{number}</span><h3>{title}</h3><p>{text}</p><a href="#opportunities" aria-label={`${label}: ${title}`}>{label} <Arrow diagonal /></a></article>)}</div></section>
    <section className="opportunities" id="opportunities" aria-labelledby="opportunities-title"><div className="opportunities-top"><div><SectionLabel>Curated opportunities</SectionLabel><h2 id="opportunities-title">Global opportunities,<br /><em>closer to home.</em></h2></div><p>A considered selection of programmes, exchanges, research and events for people ready to participate in global affairs.</p></div><div className="opportunity-filter" aria-label="Filter opportunities">{opportunityTypes.map((type) => <button className={activeType === type ? 'active' : ''} key={type} onClick={() => setActiveType(type)}>{type}</button>)}</div><div className="opportunity-board">{visible.map((item) => <article className={`opportunity-listing ${item.tone}`} key={item.title}><p className="meta">{item.organisation}<span>{item.type}</span></p><h3>{item.title}</h3><div className="listing-details"><span>{item.place}</span><span>{item.deadline}</span></div><a href="#top" aria-label={`View ${item.title}`}>View <Arrow /></a></article>)}</div><div className="board-footer"><p>Listings are reviewed before publication.</p><a className="text-link" href="#submit">Submit an opportunity <Arrow diagonal /></a></div></section>
    <section className="approach" id="approach"><div className="approach-image"><img loading="lazy" src="https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=85" alt="Young people in conversation outdoors" /></div><div className="approach-copy"><SectionLabel>Representation without exclusion</SectionLabel><h2>More voices.<br />A more representative <em>India.</em></h2><p>Greater participation from South India does not mean less space for anyone else. It means a stronger India — one whose global engagement draws on talent and perspectives from every region.</p><a className="text-link" href="#community">How to take part <Arrow diagonal /></a></div></section>
    <section className="focus" aria-labelledby="focus-title"><div><SectionLabel>Where we focus</SectionLabel><h2 id="focus-title">From regional<br />strength to global <em>exchange.</em></h2></div><div className="focus-list">{focusAreas.map((area, index) => <div key={area}><span>0{index + 1}</span><p>{area}</p><Arrow diagonal /></div>)}</div></section>
    <section className="events" id="events"><div className="events-title"><SectionLabel>In conversation</SectionLabel><h2>Ideas become real<br />when people <em>meet.</em></h2><p>Dialogues, public conversations and gatherings that bring global affairs closer to communities across South India.</p><a className="text-link" href="#top">View all events <Arrow diagonal /></a></div><article className="event-feature"><img loading="lazy" src="https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1100&q=85" alt="Audience gathered at a public discussion" /><div><p className="meta">Featured conversation format</p><h3>Diplomacy in public:<br />who gets to join<br />the conversation?</h3><a href="#top">Explore the format <Arrow /></a></div></article></section>
    <section className="insights" id="insights"><div className="insights-heading"><SectionLabel>Read / listen / learn</SectionLabel><h2>Global affairs,<br />made <em>legible.</em></h2><a className="text-link" href="#top">Explore insights <Arrow diagonal /></a></div><div className="story-grid"><article><p className="meta">Explainer · 6 min read</p><h3>How to find your first international opportunity</h3><p>Start with curiosity, not a perfect résumé.</p></article><article><p className="meta">Career guide · 8 min read</p><h3>Beyond the foreign service: paths into global affairs</h3><p>A wider field than most people realise.</p></article><article><p className="meta">Conversation · 12 min read</p><h3>What meaningful youth engagement looks like</h3><p>Making the room more open, one connection at a time.</p></article></div></section>
    <section className="community" id="community"><SectionLabel>The community</SectionLabel><h2>A place for people<br />curious about the <em>world.</em></h2><p>Students find mentors. Researchers find networks. Institutions discover talent. Everyone gets a clearer way in.</p><div className="community-actions"><a className="button button-light" href="#top">Join South Diplomacy <Arrow /></a><a className="text-link" href="#submit">Volunteer with us <Arrow diagonal /></a></div></section>
    <section className="partner" id="partner"><div><SectionLabel>For institutions & missions</SectionLabel><h2>Expand your engagement<br />across <em>South India.</em></h2></div><div><p>Connect with students, universities, entrepreneurs, researchers and policy communities through thoughtful outreach, dialogues, research and partnerships.</p><ul><li>Dialogue & events</li><li>Youth engagement</li><li>Research & outreach</li><li>Partnerships</li></ul><a className="button button-dark" href="mailto:hello@southdiplomacy.org">Partner with us <Arrow /></a></div></section>
    <section className="closing" id="submit"><p>South Diplomacy</p><h2>South India has a<br />place in the <em>world.</em></h2><div><a className="button button-light" href="#top">Join the community <Arrow /></a><a className="text-link" href="mailto:hello@southdiplomacy.org">Submit an opportunity <Arrow diagonal /></a></div></section>
    <footer><a className="brand" href="#top"><Mark /><span>South<br />Diplomacy</span></a><p>Connecting South India with the world.</p><div><a href="#opportunities">Opportunities</a><a href="#events">Events</a><a href="#insights">Insights</a><a href="mailto:hello@southdiplomacy.org">Contact</a></div></footer>
  </main>
}
